export function capitalizeSkill(skill: string): string {
  if (!skill) return skill;

  const trimmed = skill.trim();

  // List of skills that should be all uppercase (acronyms)
  const upperCaseSkills = [
    'aws',
    'gcp',
    'api',
    'sql',
    'html',
    'css',
    'php',
    'ios',
    'iot',
    'jwt',
    'rest',
    'soap',
    'xml',
    'json',
    'yaml',
    'ci/cd',
    'tdd',
    'bdd',
    'mvc',
    'mvvm',
    'nlp',
    'ddd',
    'sso',
    'iam',
    'ssl',
    'tls',
    'cnn',
    'rnn',
    'lstm',
    'ux',
    'ui',
    'ai',
    'ml',
    'bi',
    'http',
    'https',
    'ftp',
    'ssh',
    'tcp',
    'udp',
    'dns',
    'gpu',
    'cpu',
    'cli',
    'ide',
    'sdk',
    'jvm',
    'etl',
    'crm',
    'erp',
    'saas',
    'paas',
    'iaas',
    'cdn',
    'cicd',
  ];

  const lower = trimmed.toLowerCase();

  // Check if it should be uppercase
  if (upperCaseSkills.includes(lower)) {
    return trimmed.toUpperCase();
  }

  // Keep as-is for tech with dots or ends with 'js'
  if (trimmed.includes('.') || lower.endsWith('js')) {
    return trimmed;
  }

  // Special cases for common multi-word skills and brand names
  const specialCases: { [key: string]: string } = {
    'node.js': 'Node.js',
    'react.js': 'React.js',
    'vue.js': 'Vue.js',
    'next.js': 'Next.js',
    'express.js': 'Express.js',
    'nest.js': 'Nest.js',
    'react native': 'React Native',
    'react native (expo)': 'React Native (Expo)',
    'google cloud platform': 'Google Cloud Platform',
    'amazon web services': 'Amazon Web Services',
    'machine learning': 'Machine Learning',
    'deep learning': 'Deep Learning',
    'computer vision': 'Computer Vision',
    'natural language processing': 'Natural Language Processing',
    'data science': 'Data Science',
    'web development': 'Web Development',
    'mobile development': 'Mobile Development',
    'full stack': 'Full Stack',
    'full-stack': 'Full-Stack',
    'front end': 'Front End',
    'front-end': 'Front-End',
    'back end': 'Back End',
    'back-end': 'Back-End',
    devops: 'DevOps',
    github: 'GitHub',
    gitlab: 'GitLab',
    mongodb: 'MongoDB',
    postgresql: 'PostgreSQL',
    mysql: 'MySQL',
    graphql: 'GraphQL',
    javascript: 'JavaScript',
    typescript: 'TypeScript',
    nodejs: 'Node.js',
    reactjs: 'React.js',
    vuejs: 'Vue.js',
    nextjs: 'Next.js',
    expressjs: 'Express.js',
    tailwindcss: 'TailwindCSS',
    tailwind: 'Tailwind',
    kubernetes: 'Kubernetes',
    docker: 'Docker',
    redis: 'Redis',
    elasticsearch: 'Elasticsearch',
    firebase: 'Firebase',
    supabase: 'Supabase',
    vercel: 'Vercel',
    netlify: 'Netlify',
    heroku: 'Heroku',
    django: 'Django',
    flask: 'Flask',
    fastapi: 'FastAPI',
    springboot: 'Spring Boot',
    'spring boot': 'Spring Boot',
    dotnet: '.NET',
    '.net': '.NET',
    'c#': 'C#',
    'c++': 'C++',
    python: 'Python',
    java: 'Java',
    kotlin: 'Kotlin',
    swift: 'Swift',
    golang: 'Go',
    go: 'Go',
    rust: 'Rust',
    ruby: 'Ruby',
    'ruby on rails': 'Ruby on Rails',
    php: 'PHP',
    scala: 'Scala',
    elixir: 'Elixir',
    flutter: 'Flutter',
    dart: 'Dart',
    angular: 'Angular',
    svelte: 'Svelte',
    webpack: 'Webpack',
    vite: 'Vite',
    babel: 'Babel',
    jest: 'Jest',
    cypress: 'Cypress',
    selenium: 'Selenium',
    pytest: 'Pytest',
    junit: 'JUnit',
    nginx: 'Nginx',
    apache: 'Apache',
    linux: 'Linux',
    ubuntu: 'Ubuntu',
    windows: 'Windows',
    macos: 'macOS',
    android: 'Android',
    pandas: 'Pandas',
    numpy: 'NumPy',
    tensorflow: 'TensorFlow',
    pytorch: 'PyTorch',
    keras: 'Keras',
    scikit: 'Scikit-learn',
    'scikit-learn': 'Scikit-learn',
    opencv: 'OpenCV',
    langchain: 'LangChain',
  };

  if (specialCases[lower]) {
    return specialCases[lower];
  }

  // Default: Title case each word
  return trimmed
    .split(/\s+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
}
