runtime: python311

entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

env_variables:
  SUPABASE_URL: "https://aswweshgqhfbrqcrslcy.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzd3dlc2hncWhmYnJxY3JzbGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MDIwNTIsImV4cCI6MjA3MjI3ODA1Mn0.KcTslh2tO8IDllj44qIA8qDpUv0PhZyXte_xvr9o2qg"
  SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzd3dlc2hncWhmYnJxY3JzbGN5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjcwMjA1MiwiZXhwIjoyMDcyMjc4MDUyfQ.CJYGq04dvTkBBlR7kdTevK4kNmZ9HfBWkQNrKcG7JP0"
  FIRECRAWL_API_KEY: "fc-2c5eeabf4c3249719e94974e385311d4"
  ANTHROPIC_MODEL: "claude-3-haiku-20240307"

handlers:
- url: /.*
  script: auto
